export const LOAD_CATEGORY_TREE = 'LOAD_CATEGORY_TREE'
export const CHOOSE_CATEGORY_ITEM = 'CHOOSE_CATEGORY_ITEM'
export const UPDATE_CATEGORY_ITEM = 'UPDATE_CATEGORY_ITEM'
export const DELETE_CATEGORY_ITEM = 'DELETE_CATEGORY_ITEM'
export const CREATE_CATEGORY_ITEM = 'CREATE_CATEGORY_ITEM'
export const CATEGORY_STATUS = 'CATEGORY_STATUS'


export const LOAD_ACCESSORY_TABLE = 'LOAD_ACCESSORY_TABLE'
export const UPDATE_ACCESSORY_ITEM = 'UPDATE_ACCESSORY_ITEM'
export const DELETE_ACCESSORY_ITEM = 'DELETE_ACCESSORY_ITEM'
export const CREATE_ACCESSORY_ITEM = 'CREATE_ACCESSORY_ITEM'
export const ACCESSORY_STATUS = 'ACCESSORY_STATUS'


export const LOAD_CONTACT_TABLE = 'LOAD_CONTACT_TABLE'
export const UPDATE_CONTACT_ITEM = 'UPDATE_CONTACT_ITEM'
export const DELETE_CONTACT_ITEM = 'DELETE_CONTACT_ITEM'
export const CREATE_CONTACT_ITEM = 'CREATE_CONTACT_ITEM'
export const CONTACT_STATUS = 'CONTACT_STATUS'


export const LOAD_BUSINESS_SINGLE = 'LOAD_BUSINESS_SINGLE'
export const LOAD_BUSINESS_TABLE = 'LOAD_BUSINESS_TABLE'
export const UPDATE_BUSINESS_ITEM = 'UPDATE_BUSINESS_ITEM'
export const DELETE_BUSINESS_ITEM = 'DELETE_BUSINESS_ITEM'
export const CREATE_BUSINESS_ITEM = 'CREATE_BUSINESS_ITEM'
export const CONFIRM_BUSINESS_ITEM = 'CONFIRM_BUSINESS_ITEM'
export const BUSINESS_STATUS = 'BUSINESS_STATUS'


export const LOAD_RECORD_TABLE = 'LOAD_RECORD_TABLE'
export const UPDATE_RECORD_ITEM = 'UPDATE_RECORD_ITEM'
export const DELETE_RECORD_ITEM = 'DELETE_RECORD_ITEM'
export const CREATE_RECORD_ITEM = 'CREATE_RECORD_ITEM'
export const RECORD_STATUS = 'RECORD_STATUS'


export const LOAD_STOCK_TABLE = 'LOAD_STOCK_TABLE'
